### ISSUE TITLE
No module named 'pandas'

### ISSUE THREAD

**Issue by shawnyoung23** [ColinVDB/BMAT#2]
hi , i installed BMAT and tried to run BMAT.py using

sudo python3 BMAT.py

this is what it returns:

Traceback (most recent call last):
  File "BMAT.py", line 17, in <module>
    from dicom2bids import *
  File "/home/bgibrain/BMAT/BMAT/BMAT/dicom2bids.py", line 18, in <module>
    import pandas as pd
ModuleNotFoundError: No module named 'pandas'

does anyone have any ideas?

**Comment by shawnyoung23** [comment]
i have installed pandas in the terminal, and double checked using 

pip install pandas

**Comment by shawnyoung23** [comment]
solved,i use sudo to installed the software again
